version: '3'
services:
  pg:
    image: "postgres:12"
    container_name: "postgres"
    restart: always
    build:
      context: ./
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - dybi-pg:/var/lib/postgresql/data

volumes:
  dybi-pg:
    external: true
