version: '3.1'

services:
  app:
    volumes:
     - ".:/app/"
  db:
    ports:
      - "${POSTGRES_PORT}:5432"
  pg-admin:
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "github@igorilic.net"
      PGADMIN_DEFAULT_PASSWORD: "${POSTGRES_PASSWORD}"

  mailhog:
    ports:
      - "${MAILHOG_PORT}:8025"
      - "${EMAIL_PORT}:1025"