version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
  db:
    container_name: "dybi-pg"
    image: postgres:12.4-alpine
    volumes:
      - "./postgres-data:/var/lib/postgresql/data:rw"
    env_file:
      - .env
    restart: unless-stopped

  pg-admin:
    image: "dpage/pgadmin4"
    container_name: "dybi-pg-admin"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "github@igorilic.net"
      PGADMIN_DEFAULT_PASSWORD: "${POSTGRES_PASSWORD}"

  mailhog:
    image: "mailhog/mailhog:latest"
