<?php


use PHPUnit\Framework\TestCase;

class RoutesTest extends TestCase
{

    /**
     * @var object|null
     */
    protected $_object = null;

    protected bool $isRouted = false;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     * @dataProvider dp_routes
     */
    public function addRoute($url, $method, $params = [])
    {
        $router = new Routes();
        $router->add($url, "onRoute", $params, [$method]);

        $_SERVER['REQUEST_METHOD'] = "GET";
        $_GET['myUri'] = "/my/url";
        $router->route();
        $this->assertTrue($this->isRouted, "The route is not working");
    }

    public function dp_routes()
    {
        return [
            "GET" => [
                "/my/url",
                "GET"
            ]
        ];
    }
}
